Update Final Codes

diff --git a/Final Codes b/Final Codes
--- a/Final Codes
+++ b/Final Codes
@@ -304,30 +304,32 @@ done
 
 printf "\n7.16 Check Groups in /etc/passwd\n"
 for i in $(cat /etc/passwd | cut -d : -f 4 | sort -u); do 
-grep -q -P "^.*?:x:$i:" /etc/group
-if [ $? -ne 0 ]; then 
-echo "Group $i is referenced by /etc/passwd but does not exists in /etc/group"
-else
-printf "\e[32mPass - Group: $i\e[0m\n"
-fi
+	grep -q -P "^.*?:x:$i:" /etc/group
+		if [ $? -ne 0 ]; then 
+			echo "Group $i is referenced by /etc/passwd but does not exists in /etc/group"
+		else
+			printf "\e[32mPass - Group: $i\e[0m\n"
+		fi
 done
 
 
 printf "\n7.17 Check That Users Are Assigned Valid Home Directories and Home Directory Ownership is Correct\n"
 cat /etc/passwd | awk -F : '{print $1, $3, $6}' | while read user uid dir; do 
-if [ $uid -ge 1000 -a ! -d "$dir" -a $user != "nfsnobody" ]; then 
-printf "\e[31mHome directory ($dir) of user $user does not exist.\e[0m\n"
-else 
-printf "\e[32mPass - $user $dir\e[0m\n"
-fi
-done
-echo "Checking if Home directory ownership is correct"
-ls -ld $dir | awk '{print $3, $4}' | while read owner user1; do
-if [ "$owner" != "$user1" ]; then
-printf "\e[31mThe home directory ($dir) of user $user1 is owned by $owner.\e[0m\n"
-else 
-printf "\e[32mPass\e[0m\n"
-fi
+	if [ $uid -ge 1000 -a ! -d "$dir" -a $user != "nfsnobody" ]; then 
+		printf "\e[31mHome directory ($dir) of user $user does not exist.\e[0m\n"
+	elif [ ! -d $dir ] ; then
+		printf "\e[31mHome Directory of $user cannot be found!\e[0m\n"
+	else 
+		printf "\e[32mPass - $user $dir\e[0m\n"
+		echo "Checking if Home directory ownership of $user is correct"
+		ls -ld $dir | awk '{print $3, $4}' | while read owner user1; do
+		if [ "$owner" != "$user1" ] && [ $? -eq 0 ]; then
+			printf "\e[31mThe home directory ($dir) of user $user1 is owned by $owner.\e[0m\n"
+		else 
+			printf "\e[32mPass\e[0m\n"
+		fi
+		done
+	fi
 done
 
 
@@ -365,14 +367,14 @@ printf "\n7.20 Check That Reserved UIDs Are Assigned to only System Accounts\n"
 checkUsers="root bin daemon adm lp sync shutdown halt mail news uucp operator games gopher ftp nobody nscd vcsa rpc nscd vcsa rpc mailnull smmsp pcap ntp dbus avahi sshd rpcuser nfsnobody haldaemon avahi-autoipd distcache apache oprofile webalizer dovecot squid named xfs gdm sabayon usbmuxd rtkit abrt saslauth pulse postfix tcpdump"
 cat /etc/passwd | awk -F : '($3 < 500) {print $1, $3}' | while read user uid; do found=0
 for tUser in ${checkUsers}
-do
-if [ ${user} = ${tUser} ]; then
-found=1
-fi
-done
-if [ $found -eq 0 ]; then
-echo "User $user has a reserved UID ($uid)."
-fi
+	do
+		if [ ${user} = ${tUser} ]; then
+		found=1
+		fi
+	done
+	if [ $found -eq 0 ]; then
+	echo "User $user has a reserved UID ($uid)."
+	fi
 done
 
 
