Update Final Codes

diff --git a/Final Codes b/Final Codes
--- a/Final Codes
+++ b/Final Codes
@@ -154,3 +154,233 @@ else
 	printf "\033[33;31m FAIL \n"
 fi
 echo  -en "\e[0m"
+
+
+printf "\n7.11 Ensure root PATH Integrity\n"
+printf "Checking root path integrity\n"
+if [ "`echo $PATH | grep :: `" != "" ]; then
+	echo "Empty Directory in PATH (::)"
+fi
+p=`echo $PATH | sed -e 's/::/:/' -e 's/:$//' -e 's/:/ /g'`
+set -- $p
+while [ "$1" != "" ]; do
+	if [ "$1" = "." ]; then
+		echo "PATH contains ."
+		shift
+		continue
+	fi
+	if [ -d $1 ]; then
+		perm6=$(ls -ldH $1 | grep "^.....w....")
+		perm9=$(ls -ldH $1 | grep "^........w.")
+		if [ -z "$perm6" ]; then
+			printf "\e[32mPass - Group Write permission not set on directory $1\e[0m\n"
+		else
+			printf "\e[31mFail - Group Write permission set on directory $1\e[0m\n"
+			printf "Please run remediation\n"
+		fi
+		if [ -z "$perm9" ]; then
+			printf "\e[32mPass - Other Write permission not set on directory $1\e[0m\n"
+		else
+			printf "\e[31mFail - Other Write permission set on directory $1\e[0m\n"
+			printf "Please run remediation\n"
+		fi
+		dirown=`ls -ldH $1 | awk '{print $3}'`
+		if [ "$dirown" == "root" ] ; then
+			printf "\e[32mPass - $1 is owned by root\e[0m\n\n"
+		else
+			printf "\e[31mFail - $1 is not owned by root\e[0m\n"
+			printf "Please run remediation\n\n"
+		fi
+	else
+		printf "\e[31m$1 is not a directory\e[0m\n"
+	fi
+shift
+done
+
+
+printf "\n7.12 Check Permissions on User Home Directories\n"
+for RESULT in `cat /etc/passwd | egrep -v '(root|halt|sync|shutdown)' |awk -F: '($7!="/usr/sbin/nologin" && $7!="/sbin/nologin" && $7!="/bin/false") { print $6 }'`; do
+resultperm=$(ls -ld $RESULT)
+if [[ ` echo $resultperm | grep "^......w..." ` ]]; then 
+	echo "Fail, Group Write permission is set on directory $RESULT"
+else
+	echo "Pass, Group Write permission is not set on directory $RESULT"
+fi
+if [[ ` echo $resultperm | grep "^.......-.." `  ]]; then
+	echo "Pass, Other Read permission is not set on directory $RESULT"
+else
+	echo "Fail, Other Read permission is set on directory $RESULT"
+fi
+if [[ `echo $resultperm | grep "^........-."` ]]; then
+	echo "Pass, Other Write permission is not set on directory $RESULT"
+else
+	echo "Fail, Other Write permission is set on directory $RESULT"
+fi
+if [[ `echo $resultperm | grep "^.........-"` ]]; then
+	echo "Pass, Other Execute permission is not set on directory $RESULT"
+else
+	echo "Fail, Other Execute permission is set on directory $RESULT"
+fi
+done
+
+
+printf "\n7.13 Check User Dot File Permissions\n"
+printf "Checking user dot file permissions\n"
+for dir in `cat /etc/passwd | egrep -v '(root|sync|halt|shutdown)' | awk -F: '($7 != "/sbin/nologin" && $7 != "/usr/sbin/nologin" && $7 != "/bin/false") { print $6 }'`; do
+for file in $dir/.[A-Za-z0-9]*; do
+perm6=$(ls -ld $file | grep "^.....w....")
+perm9=$(ls -ld $file | grep "^........w.")
+if [ -z "$perm6" ] && [ -z "$perm9" ]; then
+	printf "\e[32mPass - $file\e[0m\n"
+else
+	printf "\e[31mFail - $file\e[0m\n"
+	printf "Please run remediation\n"
+fi
+done
+done
+
+
+printf "\n7.14 Checking Existence of and Permissions on User .netrc Files\n"
+printf "\033[0;30m Checking Permissions on User .netrc Files \n" 
+for dir in `/bin/cat /etc/passwd | /bin/egrep -v '(root|sync|halt|shutdown)' |/bin/awk -F: '($7 != "/sbin/nologin") { print $6 }'`; do
+for file in $dir/.netrc; do
+if [ ! -h "$file" -a -f "$file" ]; then
+fileperm=`/bin/ls -ld $file | /bin/cut -f1 -d" "`
+if [ `echo $fileperm | /bin/cut -c5 ` != "-" ]
+then
+printf "\033[33;32m Group Read set on $file . \n"
+else
+printf "\033[33;31m Group Read not set on $file . \n"
+fi
+if [ `echo $fileperm | /bin/cut -c6 ` != "-" ]
+then
+printf "\033[33;32m Group Write set on $file . \n"
+else
+printf "\033[33;31m Group Write not set on $file . \n"
+fi
+if [ `echo $fileperm | /bin/cut -c7 ` != "-" ]
+then
+printf "\033[33;32m Group Execute set on $file . \n"
+else
+printf "\033[33;31m Group Execute not set on $file . \n"
+fi
+if [ `echo $fileperm | /bin/cut -c8 ` != "-" ]
+then
+printf "\033[33;32m Other Read set on $file . \n"
+else
+printf "\033[33;31m Other Read not set on $file . \n"
+fi
+if [ `echo $fileperm | /bin/cut -c9 ` != "-" ]
+then
+printf "\033[33;32m Other Write set on $file . \n"
+else
+printf "\033[33;31m Other Write not set on $file . \n"
+fi
+if [ `echo $fileperm | /bin/cut -c10 ` != "-" ]
+then
+printf "\033[33;32m Other Execute set on $file . \n"
+else
+printf "\033[33;31m Other Execute not set on $file . \n"
+fi
+fi
+echo  -en "\e[0m"
+done
+done
+
+
+printf "\n7.15 Check for Presence of User .rhosts Files\n"
+printf "\033[0;30mChecking for Presence of User .rhosts Files \n"
+for dir in `/bin/cat /etc/passwd | /bin/egrep -v '(root|halt|sync|shutdown)' |/bin/awk -F: '($7 != "/sbin/nologin") { print $6 }'`; do
+for file in $dir/.rhosts; do
+if [ ! -h "$file" -a -f "$file" ]; then
+printf "\033[33;31m.rhosts file found in $dir, please delete file if it is not needed. \n"
+else
+printf "\033[33;32mNo .rhosts file found in $dir \n"
+fi
+echo  -en "\e[0m"
+done
+doneprintf "\033[0;30mChecking for Presence of User .rhosts Files \n" 
+for dir in `/bin/cat /etc/passwd | /bin/egrep -v '(root|halt|sync|shutdown)' |/bin/awk -F: '($7 != "/sbin/nologin") { print $6 }'`; do
+for file in $dir/.rhosts; do
+if [ ! -h "$file" -a -f "$file" ]; then
+printf "\033[33;31m.rhosts file found in $dir, please delete file if it is not needed. \n"
+else
+printf "\033[33;32mNo .rhosts file found in $dir \n"
+fi
+echo  -en "\e[0m"
+done
+done
+
+
+printf "\n7.16 Check Groups in /etc/passwd\n"
+for i in $(cat /etc/passwd | cut -d : -f 4 | sort -u); do 
+grep -q -P "^.*?:x:$i:" /etc/group
+if [ $? -ne 0 ]; then 
+echo "Group $i is referenced by /etc/passwd but does not exists in /etc/group"
+else
+printf "\e[32mPass\e[0m\n"
+fi
+done
+
+
+printf "\n7.17 Check That Users Are Assigned Valid Home Directories and Home Directory Ownership is Correct\n"
+cat /etc/passwd | awk -F : '{print $1, $3, $6}' | while read user uid dir; do 
+if [ $uid -ge 1000 -a ! -d "$dir" -a $user != "nfsnobody" ]; then 
+printf "\e[31mHome directory ($dir) of user $user does not exist.\e[0m\n"
+else 
+printf "\e[32mPass\e[0m\n"
+fi
+done
+echo "Checking if Home directory ownership is correct"
+ls -ld $dir | awk '{print $3, $4}' | while read owner user1; do
+if [ "$owner" != "$user1" ]; then
+printf "\e[31mThe home directory ($dir) of user $user1 is owned by $owner.\e[0m\n"
+else 
+printf "\e[32mPass\e[0m\n"
+fi
+done
+
+
+printf "\n7.18 Check for Duplicate UIDs\n"
+printf "Checking for duplicate UIDs\n"
+cat /etc/passwd| cut -f3 -d":" | sort -n | uniq -c | while read x ; do
+[ -z "${x}" ] && break
+set - $x
+if [ $1 -gt 1 ]; then
+	users=`/bin/gawk -F: '($3 == n) { print $1 }' n=$2 /etc/passwd| /usr/bin/xargs`
+	printf "\e[31mFail - Duplicate UID ($2)\e[0m\n"
+	printf "Please run remediation"
+else
+	printf "\e[32mPass - UID ($2)\e[0m\n"
+fi
+done
+
+
+printf "\n7.19 Check for Duplicate GIDs\n"
+printf "Checking for duplicate GIDs\n"
+cat /etc/group | cut -f3 -d":" | sort -n | uniq -c | while read x ; do
+[ -z "${x}" ] && break
+set - $x
+if [ $1 -gt 1 ]; then
+	grps=`/bin/gawk -F: '($3 == n) { print $1 }' n=$2 /etc/group | /usr/bin/xargs`
+	printf "\e[31mFail - Duplicate GID ($2)\e[0m\n"
+	printf "Please run remediation"
+else
+	printf "\e[32mPass - GID ($2)\e[0m\n"
+fi
+done
+
+
+printf "\n7.20 Check That Reserved UIDs Are Assigned to only System Accounts\n"
+checkUsers="root bin daemon adm lp sync shutdown halt mail news uucp operator games gopher ftp nobody nscd vcsa rpc nscd vcsa rpc mailnull smmsp pcap ntp dbus avahi sshd rpcuser nfsnobody haldaemon avahi-autoipd distcache apache oprofile webalizer dovecot squid named xfs gdm sabayon usbmuxd rtkit abrt saslauth pulse postfix tcpdump"
+cat /etc/passwd | awk -F : '($3 < 500) {print $1, $3}' | while read user uid; do found=0
+for tUser in ${checkUsers}
+do
+if [ ${user} = ${tUser} ]; then
+found=1
+fi
+done
+if [ $found -eq 0 ]; then
+echo "User $user has a reserved UID ($uid)."
+fi
+done
